const featuredDestinations = {
  cities: {
    delhi: {
      attractions: [
        "Red Fort",
        "Qutub Minar",
        "India Gate",
        "Lotus Temple",
        "Humayun's Tomb",
        "Chandni Chowk",
        "Akshardham Temple",
        "Rashtrapati Bhavan",
      ],
      daysRequired: 3,
      bestMonths: "October to March",
    },
    mumbai: {
      attractions: [
        "Gateway of India",
        "Marine Drive",
        "Siddhivinayak Temple",
        "Elephanta Caves",
        "Colaba Causeway",
        "Juhu Beach",
        "Haji Ali Dargah",
        "Chhatrapati Shivaji Maharaj Terminus",
      ],
      daysRequired: 3,
      bestMonths: "October to February",
    },
    bangalore: {
      attractions: [
        "Lalbagh Botanical Garden",
        "Cubbon Park",
        "Bangalore Palace",
        "Bannerghatta Biological Park",
        "ISKCON Temple",
        "Vidhana Soudha",
        "Commercial Street",
      ],
      daysRequired: 2,
      bestMonths: "October to February",
    },
    hyderabad: {
      attractions: [
        "Charminar",
        "Golconda Fort",
        "Ramoji Film City",
        "Hussain Sagar Lake",
        "Salar Jung Museum",
        "Chowmahalla Palace",
        "Birla Mandir",
      ],
      daysRequired: 3,
      bestMonths: "November to February",
    },
    chennai: {
      attractions: [
        "Marina Beach",
        "Kapaleeshwarar Temple",
        "Santhome Cathedral",
        "Government Museum",
        "Guindy National Park",
        "Arignar Anna Zoological Park",
        "DakshinaChitra",
      ],
      daysRequired: 2,
      bestMonths: "November to February",
    },
    kolkata: {
      attractions: [
        "Victoria Memorial",
        "Howrah Bridge",
        "Dakshineswar Kali Temple",
        "Indian Museum",
        "Park Street",
        "Eco Park",
        "Belur Math",
      ],
      daysRequired: 3,
      bestMonths: "October to February",
    },
    pune: {
      attractions: [
        "Shaniwar Wada",
        "Aga Khan Palace",
        "Dagdusheth Halwai Temple",
        "Saras Baug",
        "Sinhagad Fort",
        "Khadakwasla Dam",
        "Pataleshwar Cave Temple",
        "Osho Garden",
      ],
      daysRequired: 3,
      bestMonths: "October to March",
    },
    ahmedabad: {
      attractions: [
        "Sabarmati Ashram",
        "Adalaj Stepwell",
        "Kankaria Lake",
        "Sidi Saiyyed Mosque",
        "Science City",
        "Akshardham Temple Ahmedabad",
        "Calico Museum of Textiles",
      ],
      daysRequired: 2,
      bestMonths: "November to February",
    },
    manali: {
      attractions: [
        "Hadimba Devi Temple",
        "Solang Valley",
        "Rohtang Pass",
        "Old Manali",
        "Jogini Falls",
        "Mall Road Market Manali",
        "Vashisht Hot Water Springs",
      ],
      daysRequired: 4,
      bestMonths: "October to June",
    },
    jaipur: {
      attractions: [
        "Hawa Mahal",
        "Amer Fort",
        "City Palace",
        "Jantar Mantar",
        "Nahargarh Fort",
        "Chokhi Dhani",
        "Jaigarh Fort",
        "Birla Mandir Jaipur",
      ],
      daysRequired: 3,
      bestMonths: "October to March",
    },
    surat: {
      attractions: [
        "Dumas Beach",
        "Surat Castle",
        "Dutch Garden",
        "Science Centre",
        "Ambika Niketan Temple",
        "Gopi Talav",
        "Sarthana Nature Park",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    lucknow: {
      attractions: [
        "Bara Imambara",
        "Chhota Imambara",
        "Rumi Darwaza",
        "The Residency",
        "Ambedkar Memorial Park",
        "British Residency",
        "Janeshwar Mishra Park",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    kanpur: {
      attractions: [
        "JK Temple",
        "Allen Forest Zoo",
        "Blue World Theme Park",
        "Moti Jheel",
        "Z Square Mall",
        "Bithoor",
        "Nana Rao Park",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    nagpur: {
      attractions: [
        "Deekshabhoomi",
        "Ambazari Lake",
        "Sitabuldi Fort",
        "Futala Lake",
        "Dragon Palace Temple",
        "Zero Mile Marker",
        "Ramtek Fort Temple",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    indore: {
      attractions: [
        "Rajwada Palace",
        "Lal Bagh Palace",
        "Khajrana Ganesh Temple",
        "Sarafa Bazar",
        "Patalpani Waterfall",
        "Central Museum Indore",
        "Annapurna Temple",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    bhopal: {
      attractions: [
        "Upper Lake",
        "Van Vihar National Park",
        "Sanchi Stupa",
        "Bhimbetka Caves",
        "Taj-ul-Masajid",
        "Birla Mandir Bhopal",
        "Bharat Bhavan",
      ],
      daysRequired: 3,
      bestMonths: "October to March",
    },
    visakhapatnam: {
      attractions: [
        "Rishikonda Beach",
        "INS Kursura Submarine Museum",
        "Kailasagiri",
        "Araku Valley",
        "Borra Caves",
        "RK Beach",
        "Simhachalam Temple",
      ],
      daysRequired: 3,
      bestMonths: "October to March",
    },
    varanasi: {
      attractions: [
        "Kashi Vishwanath Temple",
        "Dashashwamedh Ghat",
        "Assi Ghat",
        "Sarnath",
        "Manikarnika Ghat",
        "Banaras Hindu University",
        "Ramnagar Fort",
      ],
      daysRequired: 2,
      bestMonths: "November to February",
    },
    amritsar: {
      attractions: [
        "Golden Temple",
        "Wagah Border",
        "Jallianwala Bagh",
        "Partition Museum",
        "Durgiana Temple",
        "Gobindgarh Fort",
        "Ram Tirath Temple",
      ],
      daysRequired: 2,
      bestMonths: "October to March",
    },
    tokyo: {
      attractions: [
        "Shibuya Crossing",
        "Tokyo Tower",
        "Senso-ji Temple",
        "Meiji Jingu",
        "Shinjuku Gyoen",
        "Akihabara",
        "Imperial Palace",
        "Ueno Park",
      ],
      daysRequired: 5,
      bestMonths: "March to May & Sept to Nov",
    },
    "new york city": {
      attractions: [
        "Statue of Liberty",
        "Times Square",
        "Central Park",
        "Empire State Building",
        "Brooklyn Bridge",
        "The MET",
        "High Line",
        "Rockefeller Center",
      ],
      daysRequired: 5,
      bestMonths: "April to June & Sept to Nov",
    },
    london: {
      attractions: [
        "London Eye",
        "Tower Bridge",
        "Big Ben",
        "British Museum",
        "Buckingham Palace",
        "Tower of London",
        "Covent Garden",
        "St. Paul's Cathedral",
      ],
      daysRequired: 4,
      bestMonths: "March to May & Sept to Oct",
    },
    paris: {
      attractions: [
        "Eiffel Tower",
        "Louvre Museum",
        "Arc de Triomphe",
        "Notre-Dame Cathedral",
        "Sacré-Cœur",
        "Champs-Élysées",
        "Palais Garnier",
        "Jardin du Luxembourg",
      ],
      daysRequired: 4,
      bestMonths: "April to June & Oct to Nov",
    },
    dubai: {
      attractions: [
        "Burj Khalifa",
        "Dubai Mall",
        "Palm Jumeirah",
        "Dubai Fountain",
        "Museum of the Future",
        "Burj Al Arab",
        "Dubai Frame",
        "Miracle Garden",
      ],
      daysRequired: 4,
      bestMonths: "November to March",
    },
    singapore: {
      attractions: [
        "Gardens by the Bay",
        "Marina Bay Sands",
        "Sentosa Island",
        "Universal Studios",
        "Merlion Park",
        "Jewel Changi",
        "Singapore Zoo",
        "Night Safari",
      ],
      daysRequired: 3,
      bestMonths: "December to June",
    },
    bangkok: {
      attractions: [
        "Grand Palace",
        "Wat Arun",
        "Wat Pho",
        "Chatuchak Market",
        "Khao San Road",
        "Siam Paragon",
        "Wat Saket",
        "Lumphini Park",
      ],
      daysRequired: 3,
      bestMonths: "November to February",
    },
    "hong kong": {
      attractions: [
        "Victoria Peak",
        "Tian Tan Buddha",
        "Disneyland",
        "Tsim Sha Tsui",
        "Ocean Park",
        "Lantau Island",
        "Star Ferry",
        "Temple Street Night Market",
      ],
      daysRequired: 4,
      bestMonths: "October to December",
    },
    shanghai: {
      attractions: [
        "The Bund",
        "Yu Garden",
        "Oriental Pearl Tower",
        "Nanjing Road",
        "Shanghai Disneyland",
        "Jade Buddha Temple",
        "Shanghai Museum",
        "Tianzifang",
      ],
      daysRequired: 3,
      bestMonths: "October to November",
    },
    beijing: {
      attractions: [
        "Great Wall",
        "Forbidden City",
        "Temple of Heaven",
        "Summer Palace",
        "Tiananmen Square",
        "Ming Tombs",
        "Beihai Park",
        "798 Art District",
      ],
      daysRequired: 4,
      bestMonths: "September to October",
    },
    istanbul: {
      attractions: [
        "Hagia Sophia",
        "Blue Mosque",
        "Topkapi Palace",
        "Grand Bazaar",
        "Galata Tower",
        "Basilica Cistern",
        "Dolmabahçe Palace",
        "Spice Bazaar",
      ],
      daysRequired: 4,
      bestMonths: "April to May & Sept to Oct",
    },
    "los angeles": {
      attractions: [
        "Hollywood Sign",
        "Griffith Observatory",
        "Santa Monica Pier",
        "The Getty",
        "Walk of Fame",
        "Venice Beach",
        "Universal Studios Hollywood",
        "Rodeo Drive",
      ],
      daysRequired: 4,
      bestMonths: "March to May & Sept to Nov",
    },
    "san francisco": {
      attractions: [
        "Golden Gate Bridge",
        "Alcatraz Island",
        "Fisherman's Wharf",
        "Lombard Street",
        "Union Square",
        "Painted Ladies",
        "Palace of Fine Arts",
        "Golden Gate Park",
      ],
      daysRequired: 3,
      bestMonths: "September to November",
    },
    toronto: {
      attractions: [
        "CN Tower",
        "Royal Ontario Museum",
        "Distillery District",
        "Casa Loma",
        "Ripley's Aquarium",
        "St. Lawrence Market",
        "High Park",
        "Art Gallery of Ontario",
      ],
      daysRequired: 3,
      bestMonths: "June to September",
    },
    sydney: {
      attractions: [
        "Sydney Opera House",
        "Harbour Bridge",
        "Bondi Beach",
        "The Rocks",
        "Taronga Zoo",
        "Darling Harbour",
        "Royal Botanic Garden",
        "Manly Beach",
      ],
      daysRequired: 4,
      bestMonths: "September to November",
    },
    melbourne: {
      attractions: [
        "Federation Square",
        "Royal Botanic Gardens",
        "Great Ocean Road",
        "Eureka Skydeck",
        "St Kilda Beach",
        "Queen Victoria Market",
        "Hosier Lane",
        "Melbourne Museum",
      ],
      daysRequired: 3,
      bestMonths: "March to May & Sept to Nov",
    },
    rome: {
      attractions: [
        "Colosseum",
        "Trevi Fountain",
        "Pantheon",
        "Roman Forum",
        "Vatican Museums",
        "St. Peter's Basilica",
        "Piazza Navona",
        "Spanish Steps",
      ],
      daysRequired: 4,
      bestMonths: "April to June & Sept to Oct",
    },
    barcelona: {
      attractions: [
        "Sagrada Família",
        "Park Güell",
        "Casa Batlló",
        "La Rambla",
        "Gothic Quarter",
        "Camp Nou",
        "Magic Fountain",
        "Barceloneta Beach",
      ],
      daysRequired: 3,
      bestMonths: "May to June & Sept to Oct",
    },
    berlin: {
      attractions: [
        "Brandenburg Gate",
        "Reichstag",
        "East Side Gallery",
        "Museum Island",
        "Checkpoint Charlie",
        "Berlin Wall Memorial",
        "Tiergarten",
        "Charlottenburg Palace",
      ],
      daysRequired: 3,
      bestMonths: "May to September",
    },
    amsterdam: {
      attractions: [
        "Rijksmuseum",
        "Anne Frank House",
        "Van Gogh Museum",
        "Canal Cruise",
        "Vondelpark",
        "Dam Square",
        "Heineken Experience",
        "Jordan District",
      ],
      daysRequired: 3,
      bestMonths: "April to May & Sept to Nov",
    },
    vienna: {
      attractions: [
        "Schönbrunn Palace",
        "St. Stephen's Cathedral",
        "Belvedere Palace",
        "Vienna State Opera",
        "Hofburg",
        "Prater",
        "Museumsquartier",
        "Naschmarkt",
      ],
      daysRequired: 3,
      bestMonths: "April to May & Sept to Oct",
    },
    prague: {
      attractions: [
        "Charles Bridge",
        "Prague Castle",
        "Old Town Square",
        "Astronomical Clock",
        "St. Vitus Cathedral",
        "Jewish Quarter",
        "Dancing House",
        "Petrin Hill",
      ],
      daysRequired: 3,
      bestMonths: "May to June & Sept to Oct",
    },
    budapest: {
      attractions: [
        "Parliament Building",
        "Buda Castle",
        "Fisherman's Bastion",
        "Széchenyi Thermal Bath",
        "Chain Bridge",
        "Heroes' Square",
        "Margaret Island",
        "Gellért Hill",
      ],
      daysRequired: 3,
      bestMonths: "March to May & Sept to Oct",
    },
    seoul: {
      attractions: [
        "Gyeongbokgung Palace",
        "N Seoul Tower",
        "Bukchon Hanok Village",
        "Myeong-dong",
        "Lotte World",
        "Dongdaemun Design Plaza",
        "Insadong",
        "Hangang Park",
      ],
      daysRequired: 4,
      bestMonths: "March to May & Sept to Nov",
    },
    "kuala lumpur": {
      attractions: [
        "Petronas Towers",
        "Batu Caves",
        "Merdeka Square",
        "KL Tower",
        "Bukit Bintang",
        "Sunway Lagoon",
        "Perdana Botanical Garden",
        "Thean Hou Temple",
      ],
      daysRequired: 2,
      bestMonths: "December to February",
    },
    jakarta: {
      attractions: [
        "National Monument (Monas)",
        "Istiqlal Mosque",
        "Old Town (Kota Tua)",
        "Taman Mini Indonesia Indah",
        "Ancol Dreamland",
        "Sunda Kelapa Port",
        "National Museum of Indonesia",
      ],
      daysRequired: 2,
      bestMonths: "June to September",
    },
    "mexico city": {
      attractions: [
        "Zócalo",
        "Chapultepec Castle",
        "Museum of Anthropology",
        "Palacio de Bellas Artes",
        "Frida Kahlo Museum",
        "Teotihuacan",
        "Xochimilco",
        "Basilica of Our Lady of Guadalupe",
      ],
      daysRequired: 5,
      bestMonths: "March to May",
    },
    cairo: {
      attractions: [
        "Pyramids of Giza",
        "Egyptian Museum",
        "Khan el-Khalili",
        "Al-Azhar Mosque",
        "Citadel of Saladin",
        "Nile River Cruise",
        "Saqqara Necropolis",
        "Old Cairo (Coptic Cairo)",
      ],
      daysRequired: 3,
      bestMonths: "October to April",
    },
    moscow: {
      attractions: [
        "Red Square",
        "Kremlin",
        "Saint Basil's Cathedral",
        "Bolshoi Theatre",
        "Gorky Park",
        "Metro Stations Tour",
        "Tretyakov Gallery",
        "Victory Park",
      ],
      daysRequired: 4,
      bestMonths: "May to September",
    },
    lagos: {
      attractions: [
        "Lekki Conservation Centre",
        "Nike Art Gallery",
        "Tarkwa Bay Beach",
        "National Museum Lagos",
        "Freedom Park",
        "Terra Kulture",
        "Elegushi Beach",
      ],
      daysRequired: 3,
      bestMonths: "November to February",
    },
  },

  states: {
    maharashtra: {
      attractions: [
        "Gateway of India",
        "Marine Drive Mumbai",
        "Elephanta Caves",
        "Shaniwar Wada Pune",
        "Aga Khan Palace",
        "Sinhagad Fort",
        "Lonavala Lake",
        "Khandala Sunset Point",
        "Tiger's Leap",
        "Ajanta Caves",
        "Ellora Caves",
        "Bibi Ka Maqbara",
        "Mahabaleshwar",
        "Panchgani",
        "Pratapgad Fort",
        "Shirdi Saibaba Temple",
        "Trimbakeshwar Temple",
        "Sula Vineyards",
        "Tadoba National Park",
        "Khandala",
        "Lavasa",
      ], // 21 spots = 7 Days
      daysRequired: 8,
      bestMonths: "October to March",
    },
    rajasthan: {
      attractions: [
        "Hawa Mahal",
        "Amer Fort Jaipur",
        "City Palace Jaipur",
        "Lake Pichola Udaipur",
        "City Palace Udaipur",
        "Jag Mandir",
        "Mehrangarh Fort",
        "Jaswant Thada",
        "Umaid Bhawan Palace",
        "Jaisalmer Fort",
        "Sam Sand Dunes",
        "Patwon Ki Haveli",
        "Pushkar Lake",
        "Brahma Temple Pushkar",
        "Savitri Mata Temple",
        "Ranthambore National Park",
        "Chittorgarh Fort",
        "Mount Abu",
        "Dilwara Temples",
        "Nakki Lake",
        "Kumbhalgarh Fort",
        "Junagarh Fort Bikaner",
        "Karni Mata Temple",
        "Gajner Palace",
        "Bundi Stepwells",
        "Taragarh Fort",
        "Chaurasi Khambon Ki Chhatri",
      ], // 27 spots = 9 Days
      daysRequired: 10,
      bestMonths: "October to March",
    },
    "uttar pradesh": {
      attractions: [
        "Taj Mahal",
        "Agra Fort",
        "Fatehpur Sikri",
        "Kashi Vishwanath Temple",
        "Dashashwamedh Ghat",
        "Sarnath",
        "Bara Imambara",
        "Chhota Imambara",
        "Rumi Darwaza",
        "Mathura Krishna Janmabhoomi",
        "Banke Bihari Temple Vrindavan",
        "Prem Mandir",
        "Jhansi Fort",
        "Kushinagar",
        "Ayodhya Ram Mandir",
        "Sangam Prayagraj",
        "Anand Bhavan",
        "Khusro Bagh",
      ], // 18 spots = 6 Days
      daysRequired: 7,
      bestMonths: "October to March",
    },
    "tamil nadu": {
      attractions: [
        "Marina Beach",
        "Kapaleeshwarar Temple",
        "Mahabalipuram Shore Temple",
        "Meenakshi Amman Temple Madurai",
        "Thirumalai Nayakkar Mahal",
        "Gandhi Memorial Museum",
        "Ooty Lake",
        "Doddabetta Peak",
        "Botanical Garden Ooty",
        "Kodaikanal Lake",
        "Silver Cascade Falls",
        "Coaker's Walk",
        "Vivekananda Rock Memorial",
        "Thiruvalluvar Statue",
        "Padmanabhapuram Palace",
        "Rameshwaram Temple",
        "Dhanushkodi",
        "Pamban Bridge",
        "Brihadisvara Temple Thanjavur",
        "Rockfort Temple Trichy",
        "Hogenakkal Falls",
      ], // 21 spots = 7 Days
      daysRequired: 9,
      bestMonths: "November to March",
    },
    kerala: {
      attractions: [
        "Munnar Tea Gardens",
        "Eravikulam National Park",
        "Mattupetty Dam",
        "Alleppey Backwaters",
        "Alappuzha Beach",
        "Marari Beach",
        "Wayanad Edakkal Caves",
        "Banasura Sagar Dam",
        "Soochipara Falls",
        "Periyar National Park Thekkady",
        "Thekkady Lake",
        "Elephant Junction",
        "Varkala Beach",
        "Janardhana Swami Temple",
        "Kochi Fort",
        "Mattancherry Palace",
        "Athirappilly Waterfalls",
        "Kovalam Beach",
      ], // 18 spots = 6 Days
      daysRequired: 7,
      bestMonths: "September to March",
    },
    goa: {
      attractions: [
        "Calangute Beach",
        "Baga Beach",
        "Anjuna Beach",
        "Basilica of Bom Jesus",
        "Se Cathedral",
        "Reis Magos Fort",
        "Dudhsagar Falls",
        "Spice Plantation Goa",
        "Bhagwan Mahavir Sanctuary",
        "Palolem Beach",
        "Panjim Fontainhas",
        "Immaculate Conception Church",
        "Fort Aguada",
        "Chapora Fort",
        "Candolim Beach",
      ], // 15 spots = 5 Days
      daysRequired: 5,
      bestMonths: "November to February",
    },
    "himachal pradesh": {
      attractions: [
        "Shimla Mall Road",
        "The Ridge Shimla",
        "Jakhu Temple",
        "Hadimba Devi Temple Manali",
        "Solang Valley",
        "Rohtang Pass",
        "Dharamshala Cricket Stadium",
        "Bhagsunag Falls",
        "McLeod Ganj",
        "Key Monastery Spiti",
        "Chandratal Lake",
        "Kaza Spiti",
        "Kasol Parvati River",
        "Manikaran Sahib",
        "Tosh Village",
        "Khajjiar Lake Dalhousie",
        "Panchpula",
        "Dainkund Peak",
        "Kullu River Rafting",
        "Naggar Castle",
        "Beas River",
      ], // 21 spots = 7 Days
      daysRequired: 9,
      bestMonths: "March to June & Sept to Nov",
    },
    uttarakhand: {
      attractions: [
        "Rishikesh Laxman Jhula",
        "Ram Jhula",
        "Triveni Ghat",
        "Nainital Lake",
        "Snow View Point",
        "Tiffin Top",
        "Mussoorie Kempty Falls",
        "Gun Hill",
        "Camel's Back Road",
        "Valley of Flowers",
        "Hemkund Sahib",
        "Joshimath",
        "Har Ki Pauri Haridwar",
        "Mansa Devi Temple",
        "Chandi Devi Temple",
        "Auli Ski Resort",
        "Artificial Lake Auli",
        "Gorson Bugyal",
        "Jim Corbett National Park",
        "Corbett Falls",
        "Garjiya Devi Temple",
      ], // 21 spots = 7 Days
      daysRequired: 8,
      bestMonths: "March to June & Oct to Nov",
    },
    "jammu & kashmir": {
      attractions: [
        "Dal Lake Srinagar",
        "Shalimar Bagh",
        "Nishat Bagh",
        "Gulmarg Gondola Ride",
        "Khilanmarg",
        "Alpathar Lake",
        "Pahalgam Betaab Valley",
        "Aru Valley",
        "Chandanwari",
        "Sonamarg Thajiwas Glacier",
        "Zoji La Pass",
        "Baltal Valley",
        "Vaishno Devi Katra",
        "Ardh Kuwari Cave",
        "Bhairon Nath Temple",
        "Shankaracharya Temple",
        "Jamia Masjid Srinagar",
        "Hazratbal Shrine",
      ], // 18 spots = 6 Days
      daysRequired: 7,
      bestMonths: "March to August",
    },

    california: {
      attractions: [
        "Golden Gate Bridge",
        "Alcatraz Island",
        "Fisherman's Wharf",
        "Yosemite Valley",
        "Glacier Point",
        "Mariposa Grove",
        "Hollywood Walk of Fame",
        "Griffith Observatory",
        "Santa Monica Pier",
        "Disneyland Park",
        "Disney California Adventure",
        "Downtown Disney",
        "Big Sur Bixby Bridge",
        "Pfeiffer Beach",
        "Hearst Castle",
        "Napa Valley Wine Train",
        "Castello di Amorosa",
        "Old Howell Mountain Road",
        "Lake Tahoe",
        "Death Valley",
        "Joshua Tree National Park",
        "San Diego Zoo",
        "Balboa Park",
        "La Jolla Cove",
        "Monterey Bay Aquarium",
        "Cannery Row",
        "17-Mile Drive",
      ], // 27 spots = 9 Days
      daysRequired: 10,
      bestMonths: "May to September",
    },
    florida: {
      attractions: [
        "Magic Kingdom Park",
        "Epcot",
        "Disney's Animal Kingdom",
        "Everglades Airboat Tour",
        "Shark Valley",
        "Anhinga Trail",
        "South Beach Miami",
        "Art Deco Historic District",
        "Vizcaya Museum and Gardens",
        "Kennedy Space Center Visitor Complex",
        "Rocket Garden",
        "Apollo/Saturn V Center",
        "Key West Duval Street",
        "Southernmost Point Buoy",
        "Dry Tortugas National Park",
        "Universal Studios Florida",
        "Islands of Adventure",
        "Volcano Bay",
        "Busch Gardens Tampa",
        "Clearwater Beach",
        "St. Augustine Historic District",
      ], // 21 spots = 7 Days
      daysRequired: 8,
      bestMonths: "November to May",
    },
    hawaii: {
      attractions: [
        "Waikiki Beach",
        "Pearl Harbor National Memorial",
        "Diamond Head State Monument",
        "Haleakala Summit",
        "Road to Hana",
        "Molokini Crater",
        "Na Pali Coast State Park",
        "Waimea Canyon State Park",
        "Hanalei Bay",
        "Hawaii Volcanoes National Park",
        "Thurston Lava Tube",
        "Punaluʻu Beach",
        "Polynesian Cultural Center",
        "Hanauma Bay Nature Preserve",
        "Akaka Falls State Park",
        "Kailua Beach Park",
        "Mauna Kea Observatory",
        "Iolani Palace",
      ], // 18 spots = 6 Days
      daysRequired: 7,
      bestMonths: "April to June & September to November",
    },
    nevada: {
      attractions: [
        "Las Vegas Strip",
        "Bellagio Fountains",
        "High Roller Observation Wheel",
        "Hoover Dam",
        "Lake Mead",
        "Mike O'Callaghan-Pat Tillman Memorial Bridge",
        "Red Rock Canyon National Conservation Area",
        "Valley of Fire State Park",
        "Seven Magic Mountains",
        "Lake Tahoe",
        "Mount Rose",
        "Great Basin National Park",
      ], // 12 spots = 4 Days
      daysRequired: 4,
      bestMonths: "March to May & September to November",
    },
    "new york": {
      attractions: [
        "Niagara Falls State Park",
        "Maid of the Mist",
        "Cave of the Winds",
        "The Adirondacks High Peaks",
        "Lake Placid",
        "Fort Ticonderoga",
        "Finger Lakes Watkins Glen State Park",
        "Taughannock Falls",
        "Corning Museum of Glass",
        "Statue of Liberty National Monument",
        "Empire State Building",
        "Central Park",
        "Montauk Point Lighthouse",
        "Cooperstown National Baseball Hall of Fame",
        "Saratoga Race Course",
        "Letchworth State Park",
        "Boldt Castle",
        "Thousand Islands",
      ], // 18 spots = 6 Days
      daysRequired: 7,
      bestMonths: "May to October",
    },
    queensland: {
      attractions: [
        "Great Barrier Reef",
        "Cairns Esplanade",
        "Kuranda Scenic Railway",
        "Gold Coast Surfers Paradise",
        "Warner Bros. Movie World",
        "Burleigh Heads",
        "Daintree Rainforest",
        "Cape Tribulation",
        "Mossman Gorge",
        "Whitsunday Islands",
        "Whitehaven Beach",
        "Hamilton Island",
        "K'gari Fraser Island",
        "Lake McKenzie",
        "Eli Creek",
        "Sunshine Coast Noosa Main Beach",
        "Noosa National Park",
        "Glass House Mountains",
        "Lone Pine Koala Sanctuary",
        "South Bank Parklands Brisbane",
        "Story Bridge",
      ], // 21 spots = 7 full days
      daysRequired: 10,
      bestMonths: "May to October",
    },
    "new south wales": {
      attractions: [
        "Sydney Opera House",
        "Sydney Harbour Bridge",
        "The Rocks",
        "Blue Mountains Three Sisters",
        "Scenic World Blue Mountains",
        "Wentworth Falls",
        "Bondi Beach",
        "Coogee to Bondi Coastal Walk",
        "Manly Ferry",
        "Byron Bay Lighthouse",
        "Main Beach Byron Bay",
        "Wategos Beach",
        "Hunter Valley Gardens",
        "Audrey Wilkinson Winery",
        "Hot Air Balloon Hunter Valley",
        "Jervis Bay Hyams Beach",
        "Booderee National Park",
        "Point Perpendicular",
        "Port Stephens Sand Dunes",
        "Solitary Islands",
        "Mount Kosciuszko",
      ], // 21 spots = 7 full days
      daysRequired: 8,
      bestMonths: "September to November & March to May",
    },
    bavaria: {
      attractions: [
        "Neuschwanstein Castle",
        "Hohenschwangau Castle",
        "Museum of the Bavarian Kings",
        "Marienplatz Munich",
        "Frauenkirche",
        "English Garden Munich",
        "Zugspitze Mountain",
        "Eibsee Lake",
        "Partnach Gorge",
        "Eagle's Nest",
        "Berchtesgaden Salt Mine",
        "Lake Konigssee St. Bartholomew's Church",
        "Rothenburg ob der Tauber",
        "Night Watchman Tour",
        "Medieval Crime Museum",
        "Linderhof Palace",
        "Nymphenburg Palace",
        "Dachau Memorial Site",
      ], // 18 spots = 6 full days
      daysRequired: 7,
      bestMonths: "May to September",
    },
    "île-de-france": {
      attractions: [
        "Eiffel Tower",
        "Trocadéro Gardens",
        "River Seine Cruise",
        "Palace of Versailles",
        "The Hall of Mirrors",
        "Gardens of Versailles",
        "Louvre Museum",
        "Tuileries Garden",
        "Palais-Royal",
        "Disneyland Paris",
        "Walt Disney Studios Park",
        "Disney Village",
        "Fontainebleau Forest",
        "Château de Fontainebleau",
        "Barbizon Village",
        "Basilica of Saint-Denis",
        "Stade de France",
        "Marché de Saint-Ouen",
      ], // 18 spots = 6 full days
      daysRequired: 6,
      bestMonths: "April to June & September to October",
    },
    "provence-alpes-côte d’azur": {
      attractions: [
        "Promenade des Anglais Nice",
        "Castle Hill Nice",
        "Old Town Vieux Nice",
        "Verdon Gorge",
        "Moustiers-Sainte-Marie",
        "Lake of Sainte-Croix",
        "Palais des Papes Avignon",
        "Pont d'Avignon",
        "Les Halles d'Avignon",
        "Saint-Tropez Harbor",
        "Pampelonne Beach",
        "Citadelle de Saint-Tropez",
        "Lavender Fields Valensole",
        "Sénanque Abbey",
        "Gordes Village",
        "Cannes Croisette",
        "Palais des Festivals",
        "Îles de Lérins",
      ], // 18 spots = 6 full days
      daysRequired: 8,
      bestMonths: "May to September",
    },
    catalonia: {
      attractions: [
        "Sagrada Família",
        "Casa Batlló",
        "Casa Milà",
        "Montserrat Monastery",
        "Santa Maria de Montserrat",
        "Sant Jeroni Peak",
        "Costa Brava Cadaqués",
        "Tossa de Mar",
        "Cap de Creus",
        "Salvador Dalí Museum Figueres",
        "Girona Cathedral",
        "Game of Thrones Girona Sites",
        "Tarragona Roman Ruins",
        "Amphitheatre of Tarragona",
        "Pont del Diable",
        "Park Güell",
        "La Rambla Barcelona",
        "Gothic Quarter",
      ], // 18 spots = 6 full days
      daysRequired: 7,
      bestMonths: "April to June & September to October",
    },
    tuscany: {
      attractions: [
        "Florence Duomo",
        "Ponte Vecchio",
        "Piazza della Signoria",
        "Leaning Tower of Pisa",
        "Pisa Cathedral",
        "Baptistery of St. John",
        "Siena Piazza del Campo",
        "Siena Cathedral",
        "Torre del Mangia",
        "Chianti Vineyards",
        "San Gimignano Towers",
        "Monteriggioni Walled Town",
        "Uffizi Gallery",
        "Accademia Gallery David",
        "Boboli Gardens",
        "Val d'Orcia",
        "Pienza",
        "Montepulciano",
      ], // 18 spots = 6 full days
      daysRequired: 7,
      bestMonths: "April to June & September to October",
    },
    lombardy: {
      attractions: [
        "Milan Duomo",
        "Galleria Vittorio Emanuele II",
        "The Last Supper Mural",
        "Lake Como Bellagio",
        "Villa del Balbianello",
        "Varenna Village",
        "Lake Garda Sirmione",
        "Scaliger Castle",
        "Grotte di Catullo",
        "Teatro alla Scala",
        "Pinacoteca di Brera",
        "Navigli District",
        "Sforza Castle",
        "Parco Sempione",
        "Triennale di Milano",
        "Certosa di Pavia",
        "Mantua Ducal Palace",
        "Bergamo Upper Town",
      ], // 18 spots = 6 full days
      daysRequired: 6,
      bestMonths: "April to June & September to October",
    },
    bali: {
      attractions: [
        "Uluwatu Temple",
        "Kelingking Beach Nusa Penida",
        "Broken Beach",
        "Tegalalang Rice Terrace",
        "Ubud Art Market",
        "Tirta Empul Temple",
        "Sacred Monkey Forest Ubud",
        "Campuhan Ridge Walk",
        "Ubud Royal Palace",
        "Mount Batur Sunrise Trek",
        "Lake Batur",
        "Toyasya Hot Springs",
        "Nusa Penida Crystal Bay",
        "Angel's Billabong",
        "Diamond Beach",
        "Tanah Lot",
        "Seminyak Beach",
        "Canggu Beach Clubs",
      ], // 18 spots = 6 full days
      daysRequired: 7,
      bestMonths: "April to October",
    },
  },

  countries: {
    france: {
      attractions: [
        "Eiffel Tower",
        "Louvre Museum",
        "Notre-Dame de Paris",
        "Palace of Versailles",
        "The Hall of Mirrors",
        "Gardens of Versailles",
        "French Riviera Nice",
        "Promenade des Anglais",
        "Monaco Casino",
        "Mont Saint-Michel",
        "Saint-Malo Walled City",
        "Omaha Beach",
        "Chamonix Mont-Blanc",
        "Aiguille du Midi",
        "Mer de Glace",
        "Château de Chambord",
        "Chenonceau Castle",
        "Loire Valley Vineyards",
        "Carcassonne Medieval City",
        "Pont du Gard",
        "Palais des Papes Avignon",
        "Sainte-Chapelle",
        "Musée d'Orsay",
        "Sacré-Cœur Montmartre",
        "Verdon Gorge",
        "Saint-Tropez Harbor",
        "Cannes Croisette",
      ], // 27 spots = 9 Full Days
      daysRequired: 10,
      bestMonths: "April to June & September to October",
    },
    spain: {
      attractions: [
        "Sagrada Família",
        "Park Güell",
        "Casa Batlló",
        "Alhambra Palace Granada",
        "Generalife Gardens",
        "Albayzín District",
        "Prado Museum",
        "Royal Palace of Madrid",
        "Retiro Park",
        "Ibiza Beaches",
        "Es Vedrà",
        "Dalt Vila Ibiza",
        "Seville Cathedral",
        "Alcázar of Seville",
        "Plaza de España Seville",
        "Mezquita-Catedral de Córdoba",
        "Roman Theatre of Mérida",
        "Toledo Old City",
        "La Concha Beach San Sebastián",
        "Guggenheim Museum Bilbao",
        "Cuenca Hanging Houses",
        "Montserrat Monastery",
        "Costa Brava Beaches",
        "Dalí Theatre-Museum",
        "Tenerife Mount Teide",
        "Lanzarote Volcanic Park",
        "Majorca Caves of Drach",
      ], // 27 spots = 9 Full Days
      daysRequired: 10,
      bestMonths: "April to June & September to October",
    },
    "united states": {
      attractions: [
        "Statue of Liberty",
        "Empire State Building",
        "Times Square",
        "Grand Canyon National Park",
        "South Rim Trail",
        "Horseshoe Bend",
        "Yellowstone National Park",
        "Old Faithful Geyser",
        "Grand Prismatic Spring",
        "Walt Disney World Resort",
        "Magic Kingdom Park",
        "Epcot",
        "Golden Gate Bridge",
        "Alcatraz Island",
        "Yosemite National Park",
        "White House",
        "Lincoln Memorial",
        "Smithsonian Museums",
        "Las Vegas Strip",
        "Bellagio Fountains",
        "Hoover Dam",
        "Miami South Beach",
        "Everglades National Park",
        "Key West Duval Street",
        "Mount Rushmore",
        "Niagara Falls USA",
        "Space Needle Seattle",
        "Hollywood Sign",
        "Santa Monica Pier",
        "Universal Studios Hollywood",
        "French Quarter New Orleans",
        "Great Smoky Mountains",
        "Bryce Canyon",
      ], // 33 spots = 11 Full Days
      daysRequired: 14,
      bestMonths: "April to June & September to November",
    },
    china: {
      attractions: [
        "Great Wall of China Mutianyu",
        "Forbidden City",
        "Temple of Heaven",
        "Terracotta Army Xi'an",
        "Xi'an City Wall",
        "Giant Wild Goose Pagoda",
        "The Bund Shanghai",
        "Yu Garden",
        "Shanghai Tower",
        "Li River Cruise",
        "Yangshuo West Street",
        "Reed Flute Cave",
        "Potala Palace Lhasa",
        "Jokhang Temple",
        "Namtso Lake",
        "Zhangjiajie National Forest Park",
        "Tianmen Mountain",
        "Glass Bridge Zhangjiajie",
        "Chengdu Research Base of Giant Panda",
        "Leshan Giant Buddha",
        "Mount Emei",
        "Summer Palace Beijing",
        "Ming Tombs",
        "798 Art District",
        "West Lake Hangzhou",
        "Lijiang Old Town",
        "Tiger Leaping Gorge",
        "Jiuzhaigou Valley",
        "Huangshan Yellow Mountain",
        "Longmen Grottoes",
      ], // 30 spots = 10 Full Days
      daysRequired: 12,
      bestMonths: "September to October & April to May",
    },
    italy: {
      attractions: [
        "Colosseum",
        "Roman Forum",
        "Pantheon Rome",
        "Venice Grand Canal",
        "St. Mark's Basilica",
        "Doger's Palace",
        "Florence Duomo",
        "Uffizi Gallery",
        "Ponte Vecchio",
        "Amalfi Coast Positano",
        "Ravello Gardens",
        "Blue Grotto Capri",
        "Leaning Tower of Pisa",
        "Piazza dei Miracoli",
        "Pisa Baptistery",
        "Vatican Museums",
        "St. Peter's Basilica",
        "Sistine Chapel",
        "Lake Como Bellagio",
        "Villa del Balbianello",
        "Duomo di Milano",
        "Pompeii Ruins",
        "Mount Vesuvius",
        "Herculaneum",
        "Siena Piazza del Campo",
        "San Gimignano Towers",
        "Valley of the Temples Sicily",
        "Cinque Terre Riomaggiore",
        "Vernazza Village",
        "Manarola Scenic View",
      ], // 30 spots = 10 Full Days
      daysRequired: 12,
      bestMonths: "April to June & September to October",
    },
    turkey: {
      attractions: [
        "Hagia Sophia",
        "Topkapi Palace",
        "Blue Mosque",
        "Cappadocia Fairy Chimneys",
        "Goreme Open Air Museum",
        "Uchisar Castle",
        "Pamukkale Thermal Pools",
        "Hierapolis Ruins",
        "Cleopatra Antique Pool",
        "Ephesus Ancient City",
        "Temple of Artemis",
        "House of Virgin Mary",
        "Grand Bazaar Istanbul",
        "Spice Bazaar",
        "Galata Tower",
        "Antalya Old Town Kaleiçi",
        "Hadrian's Gate",
        "Düden Waterfalls",
        "Mount Nemrut",
        "Sumela Monastery",
        "Ani Ruins",
        "Bodrum Castle",
        "Bosphorus Cruise",
        "Basilica Cistern",
        "Troy Ancient City",
        "Pergamon Altar",
        "Ölüdeniz Blue Lagoon",
      ], // 27 spots = 9 Full Days
      daysRequired: 10,
      bestMonths: "April to May & September to October",
    },
    mexico: {
      attractions: [
        "Chichén Itzá",
        "Cenote Ik Kil",
        "Valladolid",
        "Tulum Ruins",
        "Playa Paraiso",
        "Sian Ka'an Biosphere",
        "Cancún Underwater Museum",
        "Isla Mujeres",
        "Xcaret Park",
        "Mexico City Zócalo",
        "Metropolitan Cathedral",
        "National Palace Mexico",
        "Teotihuacan Pyramids",
        "Pyramid of the Sun",
        "Avenue of the Dead",
        "Cozumel Palancar Reef",
        "San Gervasio Ruins",
        "El Cielo Beach",
        "Palenque Ruins",
        "Agua Azul Waterfalls",
        "San Cristóbal de las Casas",
        "Oaxaca Zócalo",
        "Monte Albán",
        "Hierve el Agua",
        "Frida Kahlo Museum",
        "Chapultepec Castle",
        "Xochimilco Floating Gardens",
      ], // 27 spots = 9 Full Days
      daysRequired: 10,
      bestMonths: "December to April",
    },
    thailand: {
      attractions: [
        "Grand Palace Bangkok",
        "Wat Phra Kaew",
        "Wat Pho Reclining Buddha",
        "Phi Phi Islands Maya Bay",
        "Bamboo Island",
        "Viking Cave",
        "Wat Arun Temple of Dawn",
        "Wat Saket Golden Mount",
        "Chatuchak Market",
        "Chiang Mai Old City",
        "Wat Phra Singh",
        "Doi Suthep Mountain",
        "Railay Beach Krabi",
        "Phra Nang Cave Beach",
        "Four Islands Tour Krabi",
        "Ayutthaya Historical Park",
        "Wat Mahathat",
        "Wat Chaiwatthanaram",
        "Erawan Waterfalls",
        "Bridge over the River Kwai",
        "Death Railway",
        "Khao Sok National Park",
        "Cheow Lan Lake",
        "James Bond Island",
        "Sukhothai Historical Park",
        "White Temple Chiang Rai",
        "Golden Triangle",
      ], // 27 spots = 9 Full Days
      daysRequired: 10,
      bestMonths: "November to February",
    },
    germany: {
      attractions: [
        "Brandenburg Gate",
        "Reichstag Building",
        "East Side Gallery",
        "Neuschwanstein Castle",
        "Hohenschwangau Castle",
        "Linderhof Palace",
        "Cologne Cathedral",
        "Hohenzollern Bridge",
        "Chocolate Museum Cologne",
        "Berlin Wall Memorial",
        "Checkpoint Charlie",
        "Museum Island",
        "Black Forest Titisee Lake",
        "Triberg Waterfalls",
        "Freiburg Minster",
        "Marienplatz Munich",
        "Frauenkirche Munich",
        "English Garden",
        "Heidelberg Castle",
        "Old Bridge Heidelberg",
        "Rothenburg ob der Tauber",
        "Dachau Concentration Camp Memorial",
        "Zugspitze Mountain",
        "Eibsee Lake",
        "Sanssouci Park",
        "Miniatur Wunderland Hamburg",
        "Elbphilharmonie",
      ], // 27 spots = 9 Days
      daysRequired: 10,
      bestMonths: "May to September",
    },
    "united kingdom": {
      attractions: [
        "Stonehenge",
        "Salisbury Cathedral",
        "Old Sarum",
        "Tower of London",
        "Tower Bridge",
        "London Eye",
        "British Museum",
        "National Gallery London",
        "St. Paul's Cathedral",
        "Edinburgh Castle",
        "Royal Mile",
        "Arthur's Seat",
        "The Roman Baths",
        "Bath Abbey",
        "Royal Crescent",
        "Giant's Causeway",
        "Carrick-a-Rede Rope Bridge",
        "Dunluce Castle",
        "Windsor Castle",
        "Buckingham Palace",
        "Westminster Abbey",
        "Loch Ness",
        "Urquhart Castle",
        "Isle of Skye",
        "The Cotswolds",
        "Stratford-upon-Avon",
        "Oxford University Colleges",
        "Canterbury Cathedral",
        "White Cliffs of Dover",
        "York Minster",
      ], // 30 spots = 10 Days
      daysRequired: 10,
      bestMonths: "May to September",
    },
    japan: {
      attractions: [
        "Mount Fuji",
        "Lake Kawaguchi",
        "Chureito Pagoda",
        "Fushimi Inari-taisha",
        "Kiyomizu-dera Temple",
        "Gion District",
        "Tokyo Skytree",
        "Senso-ji Temple",
        "Shibuya Crossing",
        "Kinkaku-ji Golden Pavilion",
        "Ryoan-ji Zen Garden",
        "Nijo Castle",
        "Arashiyama Bamboo Grove",
        "Tenryu-ji Temple",
        "Iwatayama Monkey Park",
        "Itsukushima Shrine",
        "Hiroshima Peace Memorial Park",
        "Shukkeien Garden",
        "Nara Park",
        "Todai-ji Temple",
        "Kasuga Taisha",
        "Osaka Castle",
        "Dotonbori",
        "Universal Studios Japan",
        "Himeji Castle",
        "Hakone Ropeway",
        "Owakudani",
        "Meiji Jingu Shrine",
        "Shinjuku Gyoen National Garden",
        "Akihabara Electric Town",
        "Kenrokuen Garden",
        "Shirakawa-go Village",
        "Takayama Old Town",
      ], // 33 spots = 11 Days
      daysRequired: 12,
      bestMonths: "March to May & September to November",
    },
    austria: {
      attractions: [
        "Schönbrunn Palace",
        "The Hofburg",
        "Belvedere Palace",
        "Hallstatt Village",
        "Hallstatt Skywalk",
        "Salzwelten Hallstatt",
        "Salzburg Old Town",
        "Hohensalzburg Fortress",
        "Mirabell Palace",
        "St. Stephen's Cathedral",
        "Vienna State Opera",
        "Prater Amusement Park",
        "Grossglockner High Alpine Road",
        "Pasterze Glacier",
        "Heiligenblut",
        "Innsbruck Golden Roof",
        "Nordkette Cable Car",
        "Ambras Castle",
        "Melk Abbey",
        "Lake Wolfgangsee",
        "Eisriesenwelt Ice Cave",
      ], // 21 spots = 7 Days
      daysRequired: 7,
      bestMonths: "April to May & September to October",
    },
    greece: {
      attractions: [
        "Acropolis of Athens",
        "Parthenon",
        "Ancient Agora of Athens",
        "Santorini Caldera View",
        "Oia Village",
        "Red Beach Santorini",
        "Mykonos Windmills",
        "Little Venice Mykonos",
        "Delos Island",
        "Meteora Monasteries",
        "Great Meteoron Monastery",
        "Kalabaka Town",
        "Delphi Ruins",
        "Temple of Apollo Delphi",
        "Delphi Archaeological Museum",
        "Knossos Palace Crete",
        "Heraklion Museum",
        "Samaria Gorge",
        "Rhodes Old Town",
        "Lindos Acropolis",
        "Navagio Beach Shipwreck",
        "Temple of Poseidon Sounion",
        "Epidaurus Theater",
        "Mycenae Ruins",
      ], // 24 spots = 8 Days
      daysRequired: 9,
      bestMonths: "April to June & September to October",
    },
    "united arab emirates": {
      attractions: [
        "Burj Khalifa",
        "The Dubai Mall",
        "Dubai Fountain Show",
        "Sheikh Zayed Grand Mosque",
        "Emirates Palace Abu Dhabi",
        "Qasr Al Watan",
        "Louvre Abu Dhabi",
        "Yas Island Ferrari World",
        "Warner Bros. World",
        "Palm Jumeirah",
        "Atlantis The Palm",
        "The Pointe",
        "Dubai Desert Safari",
        "Hatta Mountains",
        "Al Ain Oasis",
        "Burj Al Arab",
        "Dubai Marina Walk",
        "Museum of the Future",
        "Global Village Dubai",
        "Miracle Garden",
        "Dubai Frame",
      ], // 21 spots = 7 Days
      daysRequired: 7,
      bestMonths: "November to March",
    },
    malaysia: {
      attractions: [
        "Petronas Twin Towers",
        "KLCC Park",
        "KL Tower",
        "Batu Caves",
        "Dark Cave Malaysia",
        "Ramayana Cave",
        "Langkawi Sky Bridge",
        "Langkawi Cable Car",
        "Eagle Square",
        "Mount Kinabalu National Park",
        "Poring Hot Springs",
        "Desa Dairy Farm",
        "Genting Highlands Theme Park",
        "Chin Swee Caves Temple",
        "Awana Skyway",
        "Malacca Historic City A Famosa",
        "Jonker Street Night Market",
        "St. Paul's Hill",
        "Cameron Highlands Tea Plantation",
        "Boh Tea Centre",
        "Lavender Garden",
        "George Town Penang",
        "Kek Lok Si Temple",
        "Penang Hill",
      ], // 24 spots = 8 Days
      daysRequired: 8,
      bestMonths: "December to February & June to August",
    },
  },
};
